services:
  postgres:
    image: postgres:16
    container_name: worksphere-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worksphere

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: worksphere-redis

    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: worksphere-nginx

    ports:
      - "80:80"

    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - identity-service
      - workspace-service
      - ui

  identity-service:
    build:
      context: .
      dockerfile: ./apps/identity-service/Dockerfile

    container_name: worksphere-identity

    ports:
      - "3001:3001"

    volumes:
      - ./apps/identity-service:/app/apps/identity-service
      - /app/apps/identity-service/node_modules

    working_dir: /app/apps/identity-service

    command: npm run dev

    depends_on:
      - postgres
      - redis

  workspace-service:
    build:
      context: .
      dockerfile: ./apps/workspace-service/Dockerfile

    container_name: worksphere-workspace

    ports:
      - "3002:3002"

    volumes:
      - ./apps/workspace-service:/app/apps/workspace-service
      - /app/apps/workspace-service/node_modules

    working_dir: /app/apps/workspace-service

    command: npm run dev

    depends_on:
      - postgres
      - redis

  ui:
    build:
      context: .
      dockerfile: ./apps/ui/Dockerfile

    container_name: worksphere-frontend

    ports:
      - "4200:4200"

    volumes:
      - ./apps/ui:/app/apps/ui
      - /app/apps/ui/node_modules
      - angular_cache:/tmp/angular-cache

    working_dir: /app/apps/ui

    command: npm run dev
volumes:
  postgres_data:
  angular_cache:
