events {}

http {

    upstream identity_service {
        server worksphere-identity:3001;
    }

    upstream workspace_service {
        server worksphere-workspace:3002;
    }

    upstream frontend_service {
        server worksphere-frontend:4200;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://identity_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/workspace/ {
            proxy_pass http://workspace_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://frontend_service/;
            proxy_set_header Host $host;
        }
    }
}