export enum EmailStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  SENT = "SENT",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum EmailType {
  PASSWORD_RESET = "password-reset",
  OTP = "OTP",
  INVITE = "INVITE",
  EXPORT_USERS = "EXPORT_USERS",
  ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",
}
