FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./
COPY tsconfig.base.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install

WORKDIR /app/apps/notification-service

EXPOSE 3001

CMD ["npm", "run", "dev"]