export enum EmailStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  SENT = "SENT",
  FAILED = "FAILED",
}

export enum EmailType {
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  OTP = "OTP",
  INVITE = "INVITE",
  EXPORT_USERS = "EXPORT_USERS",
  ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",
}
