export enum OtpType {
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  LOGIN = "LOGIN",
  INVITE = "INVITE",
}

export enum OtpStatus {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  EXPIRED = "EXPIRED",
  REVOKED = "REVOKED",
}
